[package]
name = "cli"
version = "0.1.0"
edition = "2025"

[dependencies]
phx-core = { path = "../core" }
phx-registry = { path = "../registry" }
clap = { version = "4.4", features = ["derive"] }   # for CLI args
